application: echo-http-requests
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /.*
  script: app.application

